### PR TITLE
fix: preserve replaced initial template string surrounding

### LINKED ISSUE #3: [Bug]: Initial quotes aren't preserved for JS files
### Bug Description

Hi,

Thank you for an amazing plugin! The only issue I faced recently is that undoing or removing `${foo}` from a string changes backticks to double quotes, despite originally being single quotes. Please see the attached video.

### Relevant Screenshot

https://github.com/chrisgrieser/nvim-puppeteer/assets/29177689/da47ce5e-ba1f-40f6-b651-7deec59eae89

### To Reproduce

I believe this is the line to _blame_
https://github.com/chrisgrieser/nvim-puppeteer/blob/17f4ca535c5ae800dc1f5852242a8b15e7f01bd0/lua/puppeteer.lua#L52

### neovim version

```Text
0.9.2
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

### PR DESCRIPTION
**Pull request by skoch13**
Fixes https://github.com/chrisgrieser/nvim-puppeteer/issues/3

### CODE REVIEW

**Comment by chrisgrieser** [comment]
Thx for the PR! However, this solution  has a problem, when you delete {} in an existing f-string, the surround variable has never been set and is therefore still nil. 

So at least, the variable wood require a default value

**Comment by skoch13** [comment]
Oh, my bad. I should have named this PR differently in order to avoid confusion. My changes solely target JS template strings, so f-strings should remain intact. Additionally, I checked the f-strings related code and didn't see any hardcoded symbols. Therefore, changes to this method are not needed. However, I'm not very familiar with Python, so I might be wrong on this.

**Comment by chrisgrieser** [comment]
my bad, I meant string, not f-string. The issue still stands: your PR introduces the issue that if you remove braces in an existing template string, then `surrounding` is uninitialized, and therefore `nil`, making the operation error out. You still need to add a default value

**Comment by skoch13** [comment]
I have provided the `surrounding` variable with an initial value, but it seems that my pull request fixes one issue and introduces another. 😬 Still, code formatters/linters should be able to change the 'faulty' surrounding to a desired one.

**Comment by chrisgrieser** [comment]
Nah, with an initial value, it should be good I think. Not perfect, but at least a bit smarter than right now.

**Pull request merged**
